//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_id { get; set; }
        public string emp_namefirst { get; set; }
        public string emp_namelast { get; set; }
        public byte emp_status { get; set; }
        public Nullable<int> emp_dept { get; set; }
    }
}
